version: '2'

volumes:
  data:

networks:
  tier:
    driver: bridge

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: ota-update-app
    volumes:
        - ./data:/usr/src/app
        - /usr/src/app/node_modules
    ports:
      - 3000:3000
    networks:
      - tier
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: ota-update-server
    volumes:
        - ./data:/usr/src/server
        - /usr/src/server/node_modules
    networks:
      - tier
    ports:
      - 8001:8001